site_name: IOTConnect
repo_url: https://github.com/hokus15/IOTConnect
site_description: 'Python Internet Of Things integration service'
site_author: 'Jordi Morell'
nav:
    - Home: 'index.md'
    - 'Getting started': 'Getting Started.md'
    - 'Extending IOTConnect': 'Extending IOTConnect.md'
    - 'Tutorial': 'Tutorial.md'
theme:
  name: material
